builds:
  - binary: bumblebee
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

    ldflags:
      - -s -w -X cmd.AppVersion={{.Version}} -X cmd.AppBuiltBy=goreleaser -X cmd.AppCommit={{.Commit}} -X cmd.AppDateTime={{.Date}}

release:
  prerelease: auto

universal_binaries:
  - replace: false

brews:
  -
    repository:
      owner: thoughtrealm
      name: homebrew-solutions
    commit_author:
      name: hoby
      email: hoby@thoughtrealm.com
    name: bumblebee
    homepage: https://github.com/thoughtrealm/bumblebee

checksum:
  name_template: 'checksums.txt'
